PointCapacity:
  downDir: POINTCAPACITY_PATH
  headLess: True
  fileType:
  pipeLine: NGPL
  cycleSelector: BEST AVAILABLE
  pipeGroups:
    - ARLS
    - CP
    - CIG
    - EEC
    - EPNG
    - HORZ
    - KMIL
    - KMLP
    - MEP
    - MOPC
    - NGPL
    - SGP
    - SLNG
    - SNG
    - STAG
    - TGPD
    - TCP
    - WIC
    - YGS
SegmentCapacity:
  downDir: SEGMENTCAPACITY_PATH
  headLess: True
  pipeLine: NGPL
  cycleSelector: BEST AVAILABLE
  pipeGroups:
    - ARLS
    - CP
    - CIG
    - EEC
    - EPNG
    - HORZ
    - KMIL
    - KMLP
    - MEP
    - MOPC
    - NGPL
    - SGP
    - SNG
    - STAG
    - TGPD
    - TCP
    - WIC
StorageCapacity:
  downDir: STORAGECAPACITY_PATH
  headLess: True
  pipeLine: NGPL
  cycleSelector: BEST AVAILABLE
  pipeGroups:
    - ARLS
    - CIG
    - NGPL
    - SLNG
    - SNG
    - STAG
    - TGPD
    - YGS
NoNoticeActivity:
  downDir: NONOTICEACTIVITY_PATH
  headLess: True
  pipeLine: NGPL
  fileType:
  pipeGroups:
    - ARLS
    - CP
    - CIG
    - EEC
    - EPNG
    - HORZ
    - KMIL
    - KMLP
    - MEP
    - MOPC
    - NGPL
    - SGP
    - SLNG
    - SNG
    - STAG
    - TGPD
    - TCP
    - WIC
    - YGS
