cycleSelector: INTRADAY 3
downDir: SEGMENTCAPACITY_PATH
headLess: true
pipeGroups:
- ARLS
- CP
- CIG
- EEC
- EPNG
- HORZ
- KMIL
- KMLP
- MEP
- MOPC
- NGPL
- SGP
- SNG
- STAG
- TGPD
- TCP
- WIC
pipeLine: HORZ
targetDate: 2025-04-25
