basePath: ./
cycleSelector: INTRADAY 3
downDir: ./downs/PointCapacity
fileType: del
headLess: true
pipeGroups:
- ARLS
- CP
- CIG
- EEC
- EPNG
- HORZ
- KMIL
- KMLP
- MEP
- MOPC
- NGPL
- SGP
- SLNG
- SNG
- STAG
- TGPD
- TCP
- WIC
- YGS
pipeLine: NGPL
targetDate: 2025-04-23
